CREATE TABLE "edu_cost_params" (
	"stage" text PRIMARY KEY NOT NULL,
	"start_age" integer NOT NULL,
	"years" integer NOT NULL,
	"public_tuition" integer DEFAULT 0 NOT NULL,
	"private_tuition" integer DEFAULT 0 NOT NULL,
	"overseas_tuition" integer DEFAULT 0 NOT NULL,
	"extra_fee" integer DEFAULT 0 NOT NULL,
	"care_fee" integer DEFAULT 0 NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"source" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "finance_categories" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"kind" text NOT NULL,
	"parent" text NOT NULL,
	"label" text NOT NULL,
	"risk_asset" boolean DEFAULT false NOT NULL,
	"liquidity" text,
	"consumer" boolean DEFAULT false NOT NULL,
	"needs_note" boolean DEFAULT false NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"is_system" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "finance_categories_kind_label_uq" ON "finance_categories" USING btree ("kind","label");--> statement-breakpoint
CREATE INDEX "finance_categories_kind_sort_idx" ON "finance_categories" USING btree ("kind","sort_order");
--> statement-breakpoint
-- seed：系統預設細類（is_system=true，之後只能停用不能刪；後台可改名/改大類/排序）
INSERT INTO "finance_categories" ("kind","parent","label","risk_asset","liquidity","consumer","needs_note","sort_order","active","is_system") VALUES
('income', '工作', '薪資', false, NULL, false, false, 10, true, true),
('income', '工作', '執行業務所得', false, NULL, false, false, 20, true, true),
('income', '工作', '年終獎金', false, NULL, false, false, 30, true, true),
('income', '工作', '三節獎金', false, NULL, false, false, 40, true, true),
('income', '工作', '績效/季獎金', false, NULL, false, false, 50, true, true),
('income', '工作', '佣金/業績獎金', false, NULL, false, false, 60, true, true),
('income', '工作', '加班費', false, NULL, false, false, 70, true, true),
('income', '工作', '兼職', false, NULL, false, false, 80, true, true),
('income', '工作', '差旅/交通補貼', false, NULL, false, false, 90, true, true),
('income', '工作', '股票/員工分紅', false, NULL, false, false, 100, true, true),
('income', '理財', '租金收入', false, NULL, false, false, 110, true, true),
('income', '理財', '股利/利息', false, NULL, false, false, 120, true, true),
('income', '理財', '存款利息', false, NULL, false, false, 130, true, true),
('income', '理財', '基金/ETF 配息', false, NULL, false, false, 140, true, true),
('income', '理財', '債券配息', false, NULL, false, false, 150, true, true),
('income', '理財', '資本利得(已實現)', false, NULL, false, false, 160, true, true),
('income', '理財', '事業盈餘分配', false, NULL, false, false, 170, true, true),
('income', '理財', '版稅/權利金', false, NULL, false, false, 180, true, true),
('income', '理財', '加密資產收益', false, NULL, false, false, 190, true, true),
('income', '其他', '退休金/年金', false, NULL, false, false, 200, true, true),
('income', '其他', '政府補助/津貼', false, NULL, false, false, 210, true, true),
('income', '其他', '保險給付', false, NULL, false, false, 220, true, true),
('income', '其他', '贍養費/扶養費', false, NULL, false, false, 230, true, true),
('income', '其他', '親友資助', false, NULL, false, false, 240, true, true),
('income', '其他', '贈與/中獎', false, NULL, false, false, 250, true, true),
('income', '其他', '其他', false, NULL, false, true, 260, true, true),
('expense', '生活', '餐食', false, NULL, false, false, 10, true, true),
('expense', '生活', '居住(房租)', false, NULL, false, false, 20, true, true),
('expense', '生活', '管理費/修繕', false, NULL, false, false, 30, true, true),
('expense', '生活', '水電瓦斯', false, NULL, false, false, 40, true, true),
('expense', '生活', '電信網路', false, NULL, false, false, 50, true, true),
('expense', '生活', '交通/油資', false, NULL, false, false, 60, true, true),
('expense', '生活', '通勤/停車', false, NULL, false, false, 70, true, true),
('expense', '生活', '日用品', false, NULL, false, false, 80, true, true),
('expense', '生活', '醫療/健康', false, NULL, false, false, 90, true, true),
('expense', '生活', '子女教養', false, NULL, false, false, 100, true, true),
('expense', '生活', '育兒/托育', false, NULL, false, false, 110, true, true),
('expense', '消費', '治裝/美容', false, NULL, false, false, 120, true, true),
('expense', '消費', '休閒娛樂', false, NULL, false, false, 130, true, true),
('expense', '消費', '旅遊', false, NULL, false, false, 140, true, true),
('expense', '消費', '3C/家電', false, NULL, false, false, 150, true, true),
('expense', '消費', '社交應酬', false, NULL, false, false, 160, true, true),
('expense', '消費', '人情往來(紅白包)', false, NULL, false, false, 170, true, true),
('expense', '消費', '訂閱服務', false, NULL, false, false, 180, true, true),
('expense', '消費', '寵物', false, NULL, false, false, 190, true, true),
('expense', '消費', '菸酒', false, NULL, false, false, 200, true, true),
('expense', '消費', '個人成長/進修', false, NULL, false, false, 210, true, true),
('expense', '消費', '奢侈品', false, NULL, false, false, 220, true, true),
('expense', '稅賦', '綜合所得稅', false, NULL, false, false, 230, true, true),
('expense', '稅賦', '房屋稅', false, NULL, false, false, 240, true, true),
('expense', '稅賦', '地價稅', false, NULL, false, false, 250, true, true),
('expense', '稅賦', '牌照稅/燃料費', false, NULL, false, false, 260, true, true),
('expense', '稅賦', '營業稅/營所稅', false, NULL, false, false, 270, true, true),
('expense', '稅賦', '遺產稅/贈與稅', false, NULL, false, false, 280, true, true),
('expense', '稅賦', '其他稅費', false, NULL, false, false, 290, true, true),
('expense', '孝親', '孝親金', false, NULL, false, false, 300, true, true),
('expense', '孝親', '長輩生活費', false, NULL, false, false, 310, true, true),
('expense', '孝親', '長輩醫療/照護', false, NULL, false, false, 320, true, true),
('expense', '保險', '壽險保費', false, NULL, false, false, 330, true, true),
('expense', '保險', '醫療/健康險保費', false, NULL, false, false, 340, true, true),
('expense', '保險', '意外險保費', false, NULL, false, false, 350, true, true),
('expense', '保險', '投資型保單保費', false, NULL, false, false, 360, true, true),
('expense', '保險', '年金險保費', false, NULL, false, false, 370, true, true),
('expense', '保險', '車險/住宅火險', false, NULL, false, false, 380, true, true),
('expense', '保險', '勞健保自付', false, NULL, false, false, 390, true, true),
('expense', '保險', '國民年金保費', false, NULL, false, false, 400, true, true),
('expense', '其他', '慈善捐贈', false, NULL, false, false, 410, true, true),
('expense', '其他', '投資扣款/定期定額', false, NULL, false, false, 420, true, true),
('expense', '其他', '其他', false, NULL, false, true, 430, true, true),
('asset', '自用資產', '現金', false, '流動', false, false, 10, true, true),
('asset', '自用資產', '活期存款', false, '流動', false, false, 20, true, true),
('asset', '自用資產', '自住不動產', false, '固定', false, false, 30, true, true),
('asset', '自用資產', '自用車輛', false, '固定', false, false, 40, true, true),
('asset', '自用資產', '動產-珠寶名錶', false, '固定', false, false, 50, true, true),
('asset', '自用資產', '動產-藝術/收藏', false, '固定', false, false, 60, true, true),
('asset', '自用資產', '動產-3C/設備', false, '固定', false, false, 70, true, true),
('asset', '自用資產', '動產-家具家電', false, '固定', false, false, 80, true, true),
('asset', '可投資資產', '定存', false, '流動', false, false, 90, true, true),
('asset', '可投資資產', '外幣存款', false, '流動', false, false, 100, true, true),
('asset', '可投資資產', '貨幣型基金', false, '流動', false, false, 110, true, true),
('asset', '可投資資產', '儲蓄險現金價值', false, '流動', false, false, 120, true, true),
('asset', '可投資資產', '保單現金價值', false, '流動', false, false, 130, true, true),
('asset', '可投資資產', '股票', true, '流動', false, false, 140, true, true),
('asset', '可投資資產', '基金', true, '流動', false, false, 150, true, true),
('asset', '可投資資產', 'ETF', true, '流動', false, false, 160, true, true),
('asset', '可投資資產', '債券', true, '流動', false, false, 170, true, true),
('asset', '可投資資產', '期貨/選擇權', true, '流動', false, false, 180, true, true),
('asset', '可投資資產', '投資型保單', true, '流動', false, false, 190, true, true),
('asset', '可投資資產', '加密貨幣', true, '流動', false, false, 200, true, true),
('asset', '可投資資產', '黃金/貴金屬', true, '流動', false, false, 210, true, true),
('asset', '可投資資產', 'REITs', true, '流動', false, false, 220, true, true),
('asset', '可投資資產', '不動產', true, '固定', false, false, 230, true, true),
('asset', '可投資資產', '出租不動產', true, '固定', false, false, 240, true, true),
('asset', '可投資資產', '土地', true, '固定', false, false, 250, true, true),
('asset', '可投資資產', '車位', true, '固定', false, false, 260, true, true),
('asset', '可投資資產', '未上市股權/事業投資', true, '固定', false, false, 270, true, true),
('asset', '可投資資產', '私募/另類投資', true, '固定', false, false, 280, true, true),
('asset', '可投資資產', '勞退專戶', false, '固定', false, false, 290, true, true),
('asset', '可投資資產', '應收帳款/借出款', false, '固定', false, false, 300, true, true),
('asset', '可投資資產', '互助會(會錢)', false, '固定', false, false, 310, true, true),
('asset', '可投資資產', '信託資產', false, '固定', false, false, 320, true, true),
('asset', '可投資資產', '其他', false, '流動', false, true, 330, true, true),
('liability', '房貸', '自住房貸', false, NULL, false, false, 10, true, true),
('liability', '房貸', '投資房貸', false, NULL, false, false, 20, true, true),
('liability', '房貸', '二胎房貸', false, NULL, false, false, 30, true, true),
('liability', '房貸', '房屋修繕貸款', false, NULL, false, false, 40, true, true),
('liability', '車貸', '汽車貸款', false, NULL, false, false, 50, true, true),
('liability', '車貸', '機車貸款', false, NULL, false, false, 60, true, true),
('liability', '信貸', '信用貸款', false, NULL, true, false, 70, true, true),
('liability', '信貸', '信用卡循環', false, NULL, true, false, 80, true, true),
('liability', '信貸', '現金卡/預借現金', false, NULL, true, false, 90, true, true),
('liability', '信貸', '分期付款', false, NULL, true, false, 100, true, true),
('liability', '信貸', '卡債協商', false, NULL, true, false, 110, true, true),
('liability', '信貸', '就學貸款', false, NULL, false, false, 120, true, true),
('liability', '其他', '私人借款(親友)', false, NULL, false, false, 130, true, true),
('liability', '其他', '民間借貸', false, NULL, true, false, 140, true, true),
('liability', '其他', '保單借款', false, NULL, false, false, 150, true, true),
('liability', '其他', '股票質押借款', false, NULL, false, false, 160, true, true),
('liability', '其他', '不動產質借', false, NULL, false, false, 170, true, true),
('liability', '其他', '企業/營運週轉貸款', false, NULL, false, false, 180, true, true),
('liability', '其他', '融資租賃', false, NULL, false, false, 190, true, true),
('liability', '其他', '應付稅款', false, NULL, false, false, 200, true, true),
('liability', '其他', '其他', false, NULL, false, true, 210, true, true)
ON CONFLICT ("kind","label") DO NOTHING;
--> statement-breakpoint
-- seed：教育費用參數（2026/08 官方公告值；後台 /admin/edu-costs 可改）
INSERT INTO "edu_cost_params" ("stage","start_age","years","public_tuition","private_tuition","overseas_tuition","extra_fee","care_fee","sort_order","source") VALUES
('幼兒園', 3, 3, 12000, 180000, 0, 10000, 190000, 0, '教育部 0-6 歲國家一起養（公幼月繳上限 1,000）；私幼月費市場中位推估；補習才藝＝教育部統計處 106 學年幼兒園教育消費支出調查'),
('國小', 6, 6, 12000, 115000, 1200000, 60000, 190000, 1, '教育部 114 學年公私立國中小學雜費及代收代辦費收取基準；教育部統計處 108 學年國小教育消費支出調查'),
('國中', 12, 3, 13000, 114000, 1200000, 45000, 190000, 2, '教育部 114 學年公私立國中小收費基準；教育部統計處 109 學年國中教育消費支出調查'),
('高中職', 15, 3, 20000, 54000, 1400000, 21000, 200000, 3, '112 學年第 2 學期起公私立高中職學費全免（雜費/代收代辦/餐費自付）；教育部 114 學年高級中等學校學費收費數額表；教育部統計處 107 學年高中職教育消費支出調查'),
('大學', 18, 4, 55000, 65000, 1500000, 15000, 260000, 4, '教育部 114 學年大專學雜費收費基準（公立約 5.1-7.2 萬、私立約 9.4-11 萬，私立已扣 3.5 萬補助）；海外＝美英日澳留學年支出中位'),
('研究所', 22, 2, 60000, 100000, 1500000, 0, 260000, 5, '114 學年公私立碩士班學雜費（3.5 萬補助不適用研究所）'),
('博士班', 24, 4, 58000, 100000, 1500000, 0, 260000, 6, '114 學年公私立博士班學雜費')
ON CONFLICT ("stage") DO NOTHING;
